POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "WillyWonka@gmail.com",
  "name":"Willy Wonka",
  "password": "123"
}
######
######
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "jeffbizous@gmail.com",
  "password": "123"
}
######
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "jeffbizous@gmail.com",
  "name":"Jeff Bizous",
  "password": "123"
}
#####
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "Poppy@gmail.com",
  "name":"Poppy",
  "password": "456"
}
######
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "WillyWonka@gmail.com",
  "password": "123"
}

<!--
  You must type the Access token after the Bearer ....  you cen get it from the login route 
  After you type the correct informatio in the user is registered to your database if not 
  Use the register route  you can get also the assess token from the register route without need for the login  
-->
#####
GET http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTU4NDA3MDhkMTUxNzBiMDMzMDBmMSIsImlhdCI6MTcyNjMyNDE3OCwiZXhwIjoxNzI2MzI1MDc4fQ.lluB9YhwqQ-1ZNiEO1WfcAqUssglw_ZaVRUq4N7HkBc
#####
GET http://localhost:5000/api/users/66d1c4304b557156bf66f4a3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTU4NDA3MDhkMTUxNzBiMDMzMDBmMSIsImlhdCI6MTcyNjMyNDE3OCwiZXhwIjoxNzI2MzI1MDc4fQ.lluB9YhwqQ-1ZNiEO1WfcAqUssglw_ZaVRUq4N7HkBc


<!--
  You can use this route to refreash the Access token using the refresh Token that you get even from the login route 
  Or from the register route 
-->
####
POST http://localhost:5000/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDFjNDMwNGI1NTcxNTZiZjY2ZjRhMyIsImlhdCI6MTcyNTcyMjgwOSwiZXhwIjoxNzI2MzI3NjA5fQ.cykME1ZZpBVg5u15dTiwr-3N_qwk6rSDAwmvkSqS2Us"
  
}
