POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "WillyWonka@gmail.com",
  "name":"Willy Wonka",
  "password": "123"
}
######
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "Poppy@gmail.com",
  "name":"Poppy",
  "password": "456"
}
######
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "WillyWonka@gmail.com",
  "password": "123"
}

######
GET http://localhost:5000/api/auth/users
Content-Type: application/json

